FROM node:18-alpine

WORKDIR /racksapp/app

COPY ./racksapp/package.json .

RUN npm install

COPY ./racksapp .

EXPOSE 4200

ENTRYPOINT ["node_modules/.bin/ng" , "serve" , "--configuration=k8s" , "--host=0.0.0.0"]

